import tkinter
m=tkinter.Tk()
l1=tkinter.Label(m,text="Student- ID",bg="yellow",fg="red",font=("Arial",16)).grid(row=0,column=0)
l2=tkinter.Label(m,text="Student- NAME",bg="yellow",fg="red",font=("Arial",16)).grid(row=1,column=0)
l3=tkinter.Label(m,text="Student- ADDRESS",bg="yellow",fg="red",font=("Arial",16)).grid(row=2,column=0)
l4=tkinter.Label(m,text="GENDER",bg="yellow",fg="red",font=("Arial",16)).grid(row=3,column=0)
stdid=tkinter.Entry(m).grid(row=0,column=1)
stdname=tkinter.Entry(m).grid(row=1,column=1)
stdaddress=tkinter.Entry(m).grid(row=2,column=1)
c1=tkinter.Checkbutton(m,text="MALE",bg="yellow",fg="red",font=("Arial",16)).grid(row=3,column=1)
c2=tkinter.Checkbutton(m,text="FEMALE",bg="yellow",fg="red",font=("Arial",16)).grid(row=4,column=1)
img=tkinter.PhotoImage(file=r"D:\\CARTOON.png")
img1=img.subsample(7,6)
I=tkinter.Label(m,image=img1).grid(row=4,column=2)
m.mainloop()